config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'

  get "projects/selected", to: "projects#selected"

  resources :projects do
    resources :applications
  end
  resources :skill_users, only: [:new, :create, :destroy]
  resources :profiles

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user  = User.find(params[:id])
  end

  def edit
    @user   = User.find(params[:id])
    @skills = Skill.all.map {|skill| [skill.name, skill.id] }
    @user.skill_users.build unless @user.skill_users.present?
  end

  def update
     @user  = User.find(params[:id])
    if @user.update(user_params)
      redirect_to profile_path(@user)
    else
      @errors = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    (User.find(params[:id])).destroy
    redirect_to projects_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :facebook_picture_url, :cv, skill_users_attributes: [:id, :level, :skill_id])
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="container">
<div class="form-group">
 <div class="wrapper-gray">
<h1 class="text-center padding-top-40">Edit profile</h1>
<%= form_for @user, url: profile_path, class: '', id: '', html: { style: "width: 400px", class: "center-block padding-top-20" } do |f| %>
  <% if @errors.present? %>
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="text-center ">
    <% if user_signed_in? && current_user.facebook_picture_url %>
          <b><%= link_to cl_image_tag(current_user.facebook_picture_url, height: 200, width: 200, crop: :thumb, gravity: :face), edit_profile_path(current_user), class:"navbar-wagon-item navbar-wagon-link" if current_user.present? %></b>
        <% end %>
  </div>
  <br><br>
  <%= f.file_field :facebook_picture_url, class:"btn btn-primary" %>
  <%= f.hidden_field :facebook_picture_url_cache %>
  <br>
  <%= f.label :first_name, 'First name' %>
  <%= f.text_field :first_name, class: 'text form-control' %>
  <br>
  <%= f.label :last_name, 'Last name' %>
  <%= f.text_field :last_name, class: 'text form-control' %>
  <br>
  <%= f.label :email, 'Email' %>
  <%= f.text_field :email, class: 'text form-control' %>



  <h3>Select your skills</h3>
<% if @user.skill_users.last.new_record? %>
    <% 2.times do %>
      <%= f.fields_for :skill_users do |ff| %>
          <%= ff.hidden_field :id %>
            <li> <%= ff.select :skill_id, @skills, { :prompt => "Please select"}%>
             <%= ff.select :level, (0..10)%></li>
           <br>
        <% end %>
    <% end %>
  <% else%>
     <%= f.fields_for :skill_users do |ff| %>
        <%= ff.hidden_field :id %>
        <%= ff.select :skill_id, @skills, { :prompt => "Please select"}, class: 'form-control'%>
        <%= ff.select :level, (0..10),{ :prompt => "Please select"}, class:'form-control'%>
        <br>
      <% end %>
  <% end %>

  <%= f.file_field :cv, class:"btn btn-primary" %>
  <%#= f.hidden_field :cv_cache %>

  <div class="form-actions padding-bottom-40 padding-top-20">
  <%= f.submit 'Update your profile', class:"btn btn-primary" %>
    </div>
<% end %>
</div>
</div>
</div>

app/views/profiles/show.html.erb
<div class="container text-center">

  <h2><%= @user.first_name %>'s Profile</h2>
  <div class="text-center ">
      <% if user_signed_in? && current_user.facebook_picture_url %>
            <b><%= link_to cl_image_tag(current_user.facebook_picture_url, height: 200, width: 200, crop: :thumb, gravity: :face), edit_profile_path(current_user), class:"navbar-wagon-item navbar-wagon-link" if current_user.present? %></b>
          <% end %>

  </div>
  <br>
  <% if user_signed_in? && current_user.cv %>
            <b><%= link_to current_user.cv %></b>
          <% end %>
  <h3><%= @user.first_name %> <%=@user.last_name%></h3>
  <p><%= @user.email %></p>

  <h3>Skills</h3>
    <% @user.skill_users.each do |skill_user| %>
      <div class="text-center less-padded">
        <%= skill_user.skill.name %>
        <%= skill_user.level%>
      </div>
    <% end %>
  <div class="text-center less-padded">
    <h3>My Projects</h3>
    <% current_user.authored_projects.each do |project| %>
      <%= link_to "| #{project.name} |", project_path(project.id) %>
    <% end %>

  </div>
  <div class="text-center less-padded">
    <h3>My Applications</h3>
      <% @user.applications.each do |application| %>
        <%= link_to "| #{application.project.name} |", project_application_path(application.id) %>
      <% end %>
  </div>

  <div class="text-center less-padded">
    <%= link_to 'See all projects', projects_path, class:"btn" %>
    <%= link_to 'Delete my profile', profile_path(@user), method: :delete, class:"btn"%>
    <%= link_to 'Edit my profile', edit_profile_path(@user), class:"btn" %>
  </div>

</div>