config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'

  get "projects/selected", to: "projects#selected"

  resources :projects do
    resources :applications
  end
  resources :skill_users, only: [:new, :create, :destroy]
  resources :profiles

end

app/views/shared/_card.html.erb
<div class="card">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
  <img class="card-user avatar" src="user.jpg">
  <a class="card-link" href="#" ></a>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
    </div>
    <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
    </div>
    <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- <div class="footer">Here is a space for the footer.</div>
 -->
<div class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline footer-left-icons">
          <li>
            <%= link_to "https://www.facebook.com/groups/P4C11/" do %>
                <i class="fa fa-facebook"></i>
            <% end %>
          </li>
          <li>
            <%= link_to "https://twitter.com/actionaiddk" do %>
                <i class="fa fa-twitter"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="col-xs-offset-4 col-xs-4">
        <div class="footer-right-text">
          <p><strong>About</p></strong>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="navbar">
    <div class="navbar-wagon-left hidden-xs hidden-sm">
      <b><%= link_to "Projects", projects_path, class:"navbar-wagon-item navbar-wagon-link" %></b>
      <!-- Text link -->
      <b><%= link_to "Home", root_path, class:"navbar-wagon-item navbar-wagon-link" %></b>
      <!-- Text link -->
    </div>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <% if user_signed_in? %>
        <b><%= link_to "Log off", destroy_user_session_path, class:"navbar-wagon-item navbar-wagon-link", method: :delete %></b>
        <b><%= link_to "My profile", profile_path(current_user), class:"navbar-wagon-item navbar-wagon-link" if current_user.present? %></b>
      <% else %>
        <b><%= link_to "Log in", user_session_path, class:"navbar-wagon-item navbar-wagon-link" %></b>
        <b><%= link_to "Create an account", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link btn btn-medium" %></b>

        <b><%= link_to "Sign in with #{OmniAuth::Utils.camelize(:facebook)}", omniauth_authorize_path(:user, :facebook), class: "navbar-wagon-item navbar-facebook-link btn-facebook btn-medium" %></b>
      <% end %>
      <% if user_signed_in? && current_user.facebook_picture_url %>
        <b><%= link_to image_tag(current_user.facebook_picture_url, height: 50, width: 50), edit_profile_path(current_user), class:"navbar-wagon-item navbar-wagon-link" if current_user.present? %></b>
      <% end %>
    </div>
    <!-- Dropdown appearing on mobile only -->
  <div class="navbar-dropdown-right hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <!-- links in dropdown menu -->
        <li><%= link_to "My profile", edit_profile_path(current_user), class:"navbar-wagon-item navbar-wagon-link" if current_user.present? %></li>
        <li><%= link_to "Log off", destroy_user_session_path, class:"navbar-wagon-item navbar-wagon-link", method: :delete %></li>
        <li><%= link_to "See our projects", projects_path, class:"navbar-wagon-item navbar-wagon-link" %></li>
        <li><a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a></li>
        <!-- Text link -->
        <li><a href="" class="navbar-wagon-item navbar-wagon-link">About</a></li>
      </ul>
    <% else %>
    </div>
  </div>
</div>