config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'

  get "projects/selected", to: "projects#selected"

  resources :projects do
    resources :applications
  end
  resources :skill_users, only: [:new, :create, :destroy]
  resources :profiles

end

app/models/project.rb
class Project < ApplicationRecord

  has_many :project_skills, inverse_of: :project, dependent: :destroy
  has_many :applications, dependent: :destroy

  has_many :users, through: :applications
  has_many :skills, through: :project_skills
  belongs_to :author, class_name: User
  accepts_nested_attributes_for :project_skills
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def selected
    @selected_projects = Project.last(12).reverse
  end

  def index
    @projects = Project.all
  end

  def show
    @project  = Project.find(params[:id])
    @author   = User.find(@project.author_id)
    @applications = Application.where(project_id: params[:project_id])
  end

  def new
    @project  = Project.new
    @skills   = Skill.all.map {|skill| [skill.name, skill.id] }
    @project_skills = @project.project_skills.build
  end

  def create
    @project = current_user.authored_projects.build(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      @skills   = Skill.all.map {|skill| [skill.name, skill.id] }
      @errors = @project.errors.full_messages
      render :new
    end
  end

  def edit
    @project  = Project.find(params[:id])
    @skills   = Skill.all.map {|skill| [skill.name, skill.id] }
  end

  def update
     @project  = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      @errors = @project.errors.full_messages
      render :edit
    end
  end

  def destroy
    (Project.find(params[:id])).destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :author_id, project_skills_attributes: [:id, :level, :skill_id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="container less-padded">
  <h1 class="padding-top-40 text-center">Edit Project</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-7">
      <%= form_for @project, class: '', id: '' do |f| %>
        <% if @errors.present? %>
        <ul>
          <% @errors.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
        <% end %>
      <div class="form-group">
      <h4 class="padding-top-20">Name</h4>
      <%= f.text_field :name, class: 'text form-control' %>
      <h4 class="padding-top-20">Description</h4>
      <%= f.cktext_area :description, value: @project.description, class: 'text' %>
      </div>
    </div>
  <div class="col-xs-12 col-md-4 col-md-offset-1">
  <h3 class="padding-top-40">Requirements</h3>
    <div class="form-group">
      <% 1.times do %>
        <%= f.simple_fields_for :project_skills do |ff| %>
        <h4 class="padding-top-20 margin-bottom-5">Project skill</h4>
        <%= ff.select :skill_id, @skills, { :prompt => "Please select"}, class: 'form-control'%>
          <h4 class="padding-top-20 margin-bottom-5">Skill level</h4>
          <%= ff.select :level, (0..10),{ :prompt => "Please select"}, class:'form-control' %>
        <% end %>
      <% end %>
    <div class="padding-top-20">
    <%= f.submit 'Edit project', class:"btn btn-primary" %>
    </div>

  <% end %>
    </div>
    </div>
</div>
</div>

app/views/projects/index.html.erb
<% cities = ["Nairobi", "Karachi", "Delhi", "New York City", "Mumbai", "Sao Paulo", "Copenhagen", "Lahore", "Perth", "Jelling", "Paris", "Vilnius"] %>
<% times = ["60 hours", "20 hours", "10 hours", "30 hours", "5 hours"] %>


<div class='text-center less-padded'>
  <%= link_to "Create a new project", new_project_path, class: "btn btn-medium text-center padded" %>
</div>

<div class="container">
  <div class="row">
    <% sorted_projects = @projects.sort.reverse %>
    <% sorted_projects.each do |project|%>
      <div class="col-xs-4 .col-md-3">
        <div class="card text-center">
          <% project.project_skills.each do |project_skill| %>
            <%= image_tag("#{project_skill.skill.name.downcase.tr(' ', '')}.svg", height: 124, width: 124) %>
          <% end %>
          <h4><%= link_to project.name, project_path(project) %></h4>
          <div class="text-left">
          <p><strong>Skill:</strong>
          <% project.project_skills.each do |project_skill| %>
            <%= project_skill.skill.name %></p>
          <% end %>
          <p><strong> Time: </strong><%= times.sample %></p>
          <p><%= cities.sample %></p>
          <p><%= simple_format(project.description[0..80] + "...") %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container less-padded">
  <h1 class="padding-top-40 text-center">Create a Project</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-7">
      <%= form_for @project, class: '', id: '' do |f| %>
        <% if @errors.present? %>
        <ul>
          <% @errors.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
        <% end %>
      <div class="form-group">
      <h4 class="padding-top-20">Name</h4>
      <%= f.text_field :name, class: 'text form-control' %>
      <h4 class="padding-top-20">Description</h4>
      <%= f.cktext_area :description, value: 'Describe the project', class: 'text' %>
      </div>
    </div>
  <div class="col-xs-12 col-md-4 col-md-offset-1">
  <h3 class="padding-top-40">Requirements</h3>
    <div class="form-group">
      <% 1.times do %>
        <%= f.simple_fields_for :project_skills do |ff| %>
        <h4 class="padding-top-20 margin-bottom-5">Project skill</h4>
        <%= ff.select :skill_id, @skills, { :prompt => "Please select"}, class: 'form-control'%>
          <h4 class="padding-top-20 margin-bottom-5">Skill level</h4>
          <%= ff.select :level, (0..10),{ :prompt => "Please select"}, class:'form-control' %>
        <% end %>
      <% end %>
    <div class="padding-top-20">
    <%= f.submit 'Create a project', class:"btn btn-primary" %>
    </div>

  <% end %>
    </div>
    </div>
</div>
</div>

app/views/projects/selected.html.erb
<% cities = ["Nairobi", "Karachi", "Delhi", "New York City", "Mumbai", "Sao Paulo", "Copenhagen", "Lahore", "Perth", "Jelling", "Paris", "Vilnius"] %>
<% times = ["60 hours", "20 hours", "10 hours", "30 hours", "5 hours"] %>

<div class="container">
  <div class="container-fluid">
    <div class="row">
      <div class="text-center">
        <h1>Current projects</h1>
      </div>
    </div>
  </div>

  <div class="container less-padded">
    <div class="row">
      <% @selected_projects.each do |project|%>
        <div class="col-xs-4 .col-md-3">
          <div class="card text-center">
            <% project.project_skills.each do |project_skill| %>
              <%= image_tag("#{project_skill.skill.name.downcase.tr(' ', '')}.svg", height: 124, width: 124) %>
            <% end %>
            <h4><%= link_to project.name, project_path(project) %></h4>
            <div class="text-left">
            <p><strong>Skill:</strong>
            <% project.project_skills.each do |project_skill| %>
              <%= project_skill.skill.name %></p>
            <% end %>
            <p><strong> Time: </strong><%= times.sample %></p>
            <p><strong> Location: </strong><%= cities.sample %></p>
            <p><%= simple_format(project.description[0..80] + "...") %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class='text-center padded'>
    <%= link_to "Start contributing", new_profile_path, class: "btn btn-medium text-center" %>
  </div>
</div>

app/views/projects/show.html.erb
<% picture_names = ["kenyaprotest", "largegroup", "malespeaker", "nepalmarch", "pakistangroup", "peoplefence", "playinggame", "refugeecamp", "smallgroup"] %>
<% picture_name = picture_names.sample %>

<div class="container text-center">
  <div class="img-container img-responsive">
    <%= image_tag( "#{picture_name}.jpg") %>
  </div>
  <div class="center-alignment">
    <h1><%= @project.name %></h1>
    <%= simple_format(@project.description) %>
    <div class="less-padded">
      <h3>Skills Needed</h3>
      <% @project.project_skills.each do |project_skill| %>
        <span class="less-padded">
          <p>Level <%= project_skill.level%> <%= project_skill.skill.name %></p>
        </span>
      <% end %>
    </div>
  </div>

  <div class="less-padded">
    <%= link_to 'See project applicants', project_applications_path(@project), class:"btn" %>
    <%= link_to 'Apply for this project', new_project_application_path(@project), class:"btn" %>
  </div>

  <%= link_to 'All projects |', projects_path %>
  <%= link_to 'Delete this project |', project_path(@project), method: :delete %>
  <%= link_to 'Edit project', edit_project_path(@project) %>

</div>


<div class="text-center less-padded">
  <p>This project was created by <%= link_to @author.first_name, profile_path(@author.id) %></p>
</div>